### PR TITLE
Checkpoint 54 PublicProfiles

### PR DESCRIPTION
**Pull request by npauzenga**
Hey @Enriikke! Would you mind taking a look at this? I’m a little stumped. The last section of the checkpoint has us scope the displayed posts to the `current_user`. In the browser it seems to work fine. I can create a post as an authenticated user, sign out, and view the post on that user’s page. The test, however, isn’t passing. It’s getting hung up on the `@post.title`. The issue is associated with the `visible_to(current_user)` scope but I’m not quite seeing where I went wrong…

### CODE REVIEW

**Comment by npauzenga** [comment]
Sorry, this PR is totally unwieldy. I branched off of it to keep working on the subsequent checkpoints and merged back into it. The two commits --

[1344060](https://github.com/npauzenga/Bloccit/commit/1344060a0040d09dcc1c93dc2b50812d9a13966e)
[07524cd](https://github.com/npauzenga/Bloccit/commit/07524cd200bca643cdb96c1e54d8aecd98153e55)

...pertain most closely to the checkpoint in question.

**Comment by Enriikke** [comment]
Hey @npauzenga!

I read over your code but I'm not quite sure where the error is at. Would you mind posting the error message you get when running the specs? That will help me narrow it down :smile:.

**Comment by npauzenga** [comment]
Heya @Enriikke 

Ah yes, no problem --

```bash
  1) Visiting profiles not signed in shows profile
     Failure/Error: expect( page ).to have_content(@post.title)
       expected to find text "Post title" in "Home About Topics Popular Users Sign In or Sign Up Darth Vader 1 post, 1 comment Posts Comments Darth Vader commented less than a minute ago A Comment"
```
This seems straightforward but I can't seem to figure out why it works in the browser (shows the `post.title`) but doesn't work in the spec.

and then I also started getting this some of the time --

```bash
  1) Comment after_create with user's permission sends an email to users who have favorited the post
     Failure/Error: expect(FavoriteMailer).to receive(:new_comment)
       (FavoriteMailer (class)).new_comment(*(any args))
           expected: 1 time with any arguments
           received: 0 times with any arguments
```

... but I after running rspec 2-3 times that last one passes. I haven't spent time trying to debug this one yet (the other seems more pressing) but maybe it has something to do with the the test database not being reset? That's a bit of a wild guess.

**Comment by Enriikke** [comment]
Alright I found the issue! Are you ready? :smiling_imp: 

I'm actually surprised about this error. I'm doing some more digging to see if it's the expected behavior or maybe a bug in ActiveRecord. The problem is here:

```ruby
# spec/support/test_factories.rb

def associated_post(options = {})
  ...
  topic: Topic.create(name: "Topic name")
  ...
end
```

`Topic` requires a `description` and also a minimum length for it. When that line runs, a topic is created but not persisted to the database because validation fails. When it gets to the controller and actually fetches the post, the associated topic is `nil`. Then when the `visible_to` scope is applied, since the post has no topic this: `where("topics.public" => true)` is false so it filters it out. Your view is rendered correctly but it simply has no post visible for the user.

A simple solution for now is to change that line to:

```ruby
topic: Topic.create(name: "Topic name", description: "blah blah blah")
```

You actually have a validation on `Post` to check for the presence of a topic:

```ruby
validates :topic, presence: true
```

In our error, validation passes because there is in fact a topic, it's just not persisted. In my opinion, that should also catch scenarios like ours. I would think that should be the default behavior so that makes me think that it's probably a bug in AR.

**Comment by npauzenga** [comment]
Mic drop, @Enriikke out! 

Thanks for working through this! Validations have gotten me into trouble before but usually it's pretty clear the thing you're trying to do something to is `nil`. It would be nice to have `validates :topic, presence: true` proclaim "I didn't work!!" very loudly :smiley:  Thanks again for going to the trouble on this one.

**Comment by Enriikke** [comment]
No problem at all @npauzenga :smile:. It was definitely a weird one.

Feel free to merge this PR once you update the factory :shipit:

**Comment by npauzenga** [comment]
@Enriikke so you were so helpful on the last issue, care for another? I am totally unwilling merge this PR. It will outlive us all. :smile:

That second test that'd I'd mentioned is still giving some grief. --

```
    context "with user's permission" do
      it "sends an email to users who have favorited the post" do
        @user.favorites.where(post: @post).create

        allow(FavoriteMailer)
          .to receive(:new_comment)
          .with(@user, @post, @comment)
          .and_return(double(deliver_now: true))

        expect(FavoriteMailer).to receive(:new_comment)

        @comment.save
      end
```

It passes about half the time. I thought initially it was something do do with our test database but that doesn't seem right (I've installed the database cleaner gem anyway, thanks for the tip!). 

I'm a little hazy on mocking but basically we're creating a `Favorite` on `@post` and expecting FavoriteMailer to receive it's `new_comment` method after the `@comment` is saved (this is in an `after_create` method on `Comment`). It seems to create the `Comment` every time but it's not always calling the `after_create :send_favorite_emails` method.

Suggestions on where to look?

**Pull request merged**
